import pandas as pd
import numpy as np

configfile: "config/config.yaml"
include: "rules/common.smk"

# dataset
contigs = config['contigs']
dataset = config['dataset']
sample_sets = config['sample_sets']

import malariagen_data
ag3 = malariagen_data.Ag3()
df_samples = ag3.sample_metadata(sample_sets=ag3_sample_sets)

rule all:
    input:
        expand("resources/vcfs/{sample_set}.{contig}.haplotypes.vcf", sample_set=sample_sets, contig=contigs),
        expand("resources/vcfs/wholegenome/{sample_set}.vcf.gz.tbi", sample_set=sample_sets),
        expand("results/relatedness/ngsRelate.{sample_set}", sample_set=sample_sets)


include: "rules/utility.smk"
include: "rules/PopulationStructure.smk"