# Sample metadata sheet
metadata: "config/metadata.tsv"
metadataCohortColumns: 
      - 'species_gambiae_coluzzii'
      - 'mining'


# Dataset name
dataset: 'ag3_gaardian'

# If no VCF input is provided, VCFs will be written from the Zarr files
# If no Zarr input is provided, Zarr arrays will be written from the VCF files
Zarr:
      activate: True
      Genotypes: resources/snp_genotypes/all/1244-VO-GH-YAWSON-VMF00149/{contig}/calldata/GT/
      Positions: resources/snp_genotypes/all/sites/{contig}/variants/POS/
      SiteFilters: resources/site_filters/dt_20200416/gamb_colu/{contig}/variants/filter_pass
VCF:
      activate: True
      biallelic: resources/vcfs/ag3_gaardian_{contig}.biallelic.vcf.gz
      multiallelic: resources/vcfs/ag3_gaardian_{contig}.multiallelic.vcf.gz

# Paths for reference files 
reference:
      genome:
            "resources/reference/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa"

# Chromosome names. Should correspond to the reference fasta/gff files. 
contigs: ['2L', '2R', '3L', '3R', 'X']

# Modules #
PopulationStructure:
      PCA:
            activate: True
            colourColumns: ['species_gambiae_coluzzii']
      SummaryStatistics:
            activate : True
      fineStructure:
            activate: True
      NgsRelate:
            activate: False

SpatialAnalyses:
      Fst_V_GeographicDistance:
            activate: False
            minimumLocationSampleSize: 5
      FEEMS:
            activate: False

Selection:
      VariantsOfInterest: 
            activate: True
            path: "resources/VariantsOfInterest.tsv"
            map: False
            minPopSize: 10
      G12:
            activate: False
            windowSize: 
            windowStep: 
            cutHeight: 
      G123:
            activate: False
            windowSize: 1200
            windowStep: 600
            cutHeight: 6
      H12:
            activate: False
            windowSize:
            windowStep:
      PBS:
            activate: True
            windowSize: 1200
            windowStep: 600
            metadataComparatorColumn: 'mining'
      XPEHH:
            activate: True
            unphased: True
      NSL: 
            activate: True
            unphased: True

# Run analysis with compkaryo to determine proportion % karyotype
karyotype:
        activate: True
        inversions:
             - "2La"
             - "2Rj"
             - "2Rb"
             - "2Rc_col"
             - "2Rc_gam"
             - "2Rd"
             - "2Ru"
